management.endpoints.web.exposure.include=health,info,gateway

# --- Gateway Routes (neuer Prefix!) ---
spring.cloud.gateway.server.webflux.routes[0].id=project-manager
spring.cloud.gateway.server.webflux.routes[0].uri=lb://project-manager
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/projecthub/api/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1