# --- Eureka ---
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka/
eureka.instance.prefer-ip-address=true

# --- RabbitMQ ---
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin

# --- API Gateway URL --- TODO change to prod URL
api.gateway.url=https://api.3dprintverse.de/api