# --- Server Port ---
server.port=8080
# --- Offene API Endpunkte ---
app.security.permit-all-paths=/actuator/health

# --- Datenbank ---
spring.datasource.url=jdbc:mariadb://customerservice_db:3306/customerservice
spring.datasource.username=customerservice
spring.datasource.password=3qNsImNHf2dqkXATE3sjUk1sNqUTnJ4K
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
