# --- Server Port ---
server.port=8083

# --- Datenbank ---
spring.datasource.url=jdbc:mariadb://localhost:3307/projects
spring.datasource.username=devuser
spring.datasource.password=devpass
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# --- Offene API Endpunkte ---
app.security.permit-all-paths=/actuator/health,/v3/api-docs/**,/swagger-ui/**,/swagger-ui.html,/api/**,/internal/**

# --- Authentik ---

app.authentik.api.base-url=http://localhost:9000
app.authentik.api.api-token=kJqhgcmk6yIWg54QYBoF4RkqVkBsAYeHgHrBgMOdMztbTPkm9XXq9HUx3vo8
app.authentik.webhook.secret=Nothing
app.authentik.recovery.email-stage-pk=7fdd8b30-39d9-43df-97a4-ba4f6b799987