# --- Server Port ---
server.port=8080

# --- Datenbank ---
spring.datasource.url=jdbc:mariadb://project_manager_db:3306/projects
spring.datasource.username=produser
spring.datasource.password=78WQ5OSdjoUPx3n8CcZwvJRA
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# --- Offene API Endpunkte ---
app.security.permit-all-paths=/actuator/health,/internal/**

# --- Authentik ---

app.authentik.api.base-url=https://authentik.nexacode.de
app.authentik.api.api-token=v2j5Mq8LRPqS31ol4FWIWFMJZgURmg8Kzc3J0uuBfG65FXPevd8c5G5CTBYT
app.authentik.webhook.secret=78WQ5OSdjoUPx3n8CcZwvJRA
app.authentik.recovery.email-stage-pk=7fdd8b30-39d9-43df-97a4-ba4f6b799987